"""Creazione resto tabelle

Revision ID: b30100f716b0
Revises: f59ff9dc4a0c
Create Date: 2024-06-12 14:58:09.658855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30100f716b0'
down_revision: Union[str, None] = 'f59ff9dc4a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinatari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ragione_sociale', sa.String(), nullable=False),
    sa.Column('indirizzo_1', sa.String(), nullable=True),
    sa.Column('indirizzo_2', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ragione_sociale', sa.String(), nullable=False),
    sa.Column('indirizzo_1', sa.String(), nullable=True),
    sa.Column('indirizzo_2', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trasportatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ragione_sociale', sa.String(), nullable=False),
    sa.Column('indirizzo_1', sa.String(), nullable=True),
    sa.Column('indirizzo_2', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('destinazione_id', sa.Integer(), nullable=True),
    sa.Column('luogo_presa_in_carico', sa.String(), nullable=False),
    sa.Column('data_presa_in_carico', sa.Date(), nullable=True),
    sa.Column('documenti_allegati', sa.String(), nullable=True),
    sa.Column('istruzioni_mittente', sa.String(), nullable=True),
    sa.Column('porto_franco', sa.Boolean(), nullable=True),
    sa.Column('porto_assegnato', sa.Boolean(), nullable=True),
    sa.Column('rimborso', sa.String(), nullable=True),
    sa.Column('trasportatore_id', sa.Integer(), nullable=True),
    sa.Column('osservazioni_trasporto', sa.String(), nullable=True),
    sa.Column('convenzioni', sa.String(), nullable=True),
    sa.Column('compilato_a', sa.String(), nullable=True),
    sa.Column('data_compilazione', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['destinatari.id'], ),
    sa.ForeignKeyConstraint(['destinazione_id'], ['destinazioni.id'], ),
    sa.ForeignKeyConstraint(['trasportatore_id'], ['trasportatori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dettaglio_cmr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmr_id', sa.Integer(), nullable=True),
    sa.Column('u_misura', sa.String(), nullable=True),
    sa.Column('n_colli', sa.Integer(), nullable=True),
    sa.Column('imballaggio', sa.String(), nullable=True),
    sa.Column('denominazione', sa.String(), nullable=True),
    sa.Column('statistica', sa.String(), nullable=True),
    sa.Column('peso_lordo_kg', sa.Integer(), nullable=True),
    sa.Column('volume_mc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cmr_id'], ['cmr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('utenti', sa.Column('indirizzo_1', sa.String(), nullable=True))
    op.add_column('utenti', sa.Column('indirizzo_2', sa.String(), nullable=True))
    op.add_column('utenti', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utenti', 'created_at')
    op.drop_column('utenti', 'indirizzo_2')
    op.drop_column('utenti', 'indirizzo_1')
    op.drop_table('dettaglio_cmr')
    op.drop_table('cmr')
    op.drop_table('trasportatori')
    op.drop_table('destinazioni')
    op.drop_table('destinatari')
    # ### end Alembic commands ###
